-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 21:24:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CheapCRM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CheapCRM
-- -----------------------------------------------------
USE `crm` ;

-- -----------------------------------------------------
-- Table `CheapCRM`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `access_key_admin` VARCHAR(45) NOT NULL,
  `access_key_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheapCRM`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_users_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `crm`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `crm`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `photo_url` mediumblob NULL, -- Ссылка на фото
  `full_name` VARCHAR(255) NOT NULL, -- ФИО
  `active_groups` TEXT NULL, -- Активные группы
  `total_balance` DECIMAL(10, 2) DEFAULT 0, 
  `bonus_account` INT DEFAULT 0, -- Бонусный счет
  `learning_status` VARCHAR(100) NULL, -- Статус обучения
  `contacts` VARCHAR(255) NULL, -- Телефон/email
  `next_visit_date` DATETIME NULL, -- Дата следующего посещения
  PRIMARY KEY (`id`),
  INDEX `fk_clients_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `crm`.`company` (`id`)
    ON DELETE CASCADE -- Если компания удалится, удалятся и её клиенты
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
