-- MySQL Script generated by MySQL Workbench
-- Sun Jun  7 20:53:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CheapCRM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CheapCRM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CheapCRM` DEFAULT CHARACTER SET utf8 ;
USE `CheapCRM` ;

-- -----------------------------------------------------
-- Table `CheapCRM`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CheapCRM`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `access_key_admin` VARCHAR(45) NOT NULL,
  `access_key_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheapCRM`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CheapCRM`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `rank` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `birthday` DATE NULL,
  `contact` VARCHAR(45) NULL,
  `gender` VARCHAR(3) NULL,
  `avatar` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_users_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `CheapCRM`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheapCRM`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CheapCRM`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `avatar` TEXT NULL,
  `active_group` TINYINT NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL,
  `skills` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `next_visit` DATETIME NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `CheapCRM`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheapCRM`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CheapCRM`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `last_meeting` DATETIME NULL,
  `next_meeting` DATETIME NULL,
  `start_time_work` TIME NOT NULL,
  `end_time_work` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `CheapCRM`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheapCRM`.`group_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CheapCRM`.`group_members` (
  `group_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  INDEX `fk_group_members_clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_group_members_groups1_idx` (`group_id` ASC, `client_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_members_groups1`
    FOREIGN KEY (`group_id` , `client_id`)
    REFERENCES `CheapCRM`.`groups` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_members_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `CheapCRM`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
