### Check Connect
GET http://localhost:3000/checkConnect

### signin as director
POST http://localhost:3000/signin
Content-Type: application/json

{
    "company": "",
    "login": "",
    "password": ""
}